[project]
name = "text-to-speech-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elevenlabs>=2.16.0",
    "pydub>=0.25.1",
    "requests>=2.32.5",
]
